apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels: 
    app: frontend-app
    type: frontend
spec:
  template:
    metadata:
      name:  frontend-pod
      labels:
        app: frontend-pod
        type: frontend
        env: production
    spec:
     containers:
       - name: nginx-container
         image: nginx
  selector:
    matchLabels:
      type: frontend
  replicas: 2
